spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food-app
    username: app
    password: Password123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
